apiVersion: apps/v1 
kind: Deployment
metadata:
  name: currency-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: currencyservice-container
        image: gcr.io/google-samples/microservices-demo/currencyservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice 
spec:
  selector:
    app: currencyservice
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000
  type: ClusterIP
                   