apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: gcr.io/google-samples/microservices-demo/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: SHIPPING_SERVICE_HOST
          value: "shippingservice:50051"
        - name: CHECKOUT_SERVICE_ADDR
          value: "checkoutservice:5050"  
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendation-service:8080"
        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"
        - name: ADS_SERVICE_ADDR
          value: "adsservice:8080"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"
        
       
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 8080
  type: LoadBalancer
                   