apiVersion: apps/v1 
kind: Deployment
metadata:
  name: recommendation-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
      - name: recommendation-service-container
        image: gcr.io/google-samples/microservices-demo/recommendationservice:latest  
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT  
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: my-namespace 
spec:
  selector:
    app: recommendation-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
                   