apiVersion: apps/v1 
kind: Deployment
metadata:
  name: shipping-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: shippingservice-container
        image: gcr.io/google-samples/microservices-demo/shippingservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice 
spec:
  selector:
    app: shippingservice
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
  type: ClusterIP
                   